# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- development

pool:
  name: 'Dev Pool'

variables:
  buildConfiguration: 'Debug'
  artifactStagingDir: '$(Build.ArtifactStagingDirectory)'
  deploymentDir: '/var/www/kestrel_webapp/'

steps:
- script: dotnet build --configuration $(buildConfiguration) --output $(artifactStagingDir)
  displayName: 'dotnet build $(buildConfiguration)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(artifactStagingDir)'
    ArtifactName: 'drop'
    publishLocation: 'filePath'
    TargetPath: $(deploymentDir)