# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- development

pool:
  name: 'Dev Pool'

variables:
  buildConfiguration: 'Debug'
  deploymentDir: '/var/www/kestrel_webapp/'



stages:
- stage: 'build'
  displayName: 'Build'
  jobs:
  - job: 'build__build'
    displayName: 'Build application'
    workspace:
      clean: outputs
    steps:
    - script: dotnet build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
      displayName: '.NET build'
- stage: 'deploy'
  displayName: 'Deploy'
  jobs:
  - deployment: 'deploy__deploy'
    displayName: 'Deploy application'
    environment: 'nts_dev'
    strategy:
      runOnce:
        preDeploy:
          steps:
            - task: CmdLine@2
              displayName: 'Clear deployment directory'
              inputs:
                script: 'rm -rf $(deploymentDir)*'
            - task: CmdLine@2
              displayName: 'Run prep scripts (dev mode)'
              inputs:
                script: '/bin/bash $(Build.SourcesDirectory)/prep_scripts/run.sh dev $(Build.SourcesDirectory)/prep_scripts'
        deploy:
          steps:
            - task: CopyFiles@2
              displayName: 'Deploy application'
              inputs:
                SourceFolder: $(Build.ArtifactStagingDirectory)
                Contents: '**'
                TargetFolder: $(deploymentDir)
        routeTraffic:
          steps:
            - task: CmdLine@2
              displayName: 'Restart webserver'
              inputs:
                script: 'sudo systemctl restart kestrel-webapp.service'
